version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: spond_postgres
    environment:
      POSTGRES_USER: spond_user
      POSTGRES_PASSWORD: spond_password
      POSTGRES_DB: spond_club
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - spond-network

volumes:
  postgres_data:

networks:
  spond-network:
    driver: bridge